DEFAULT_TRANSLATION = "kjv"

AVAILABLE_TRANSLATIONS = ["asv", "kjv"]

TRANSLATIONS_PATHS = {
    "asv": "bibles/asv.sqlite",
    "kjv": "bibles/kjv.sqlite"
}

TRANSLATIONS_NAMES = {
    "English": [
        {
            "abbreviation": "asv",
            "description": "American Standard Version (1901)"
        },
        {
            "abbreviation": "kjv",
            "description": "King James Version"
        }]}

MAX_VERSES = 200  # Default max number of verses to return

BIBLE_BOOKS = [
    {"name": "genesis", "abbreviation": "gen", "number": 1, "chapters": 50, "testament": "old", "type": "historical",
        "author": "Moses", "language": "Hebrew", "description": "First book of the Bible, traditionally attributed to Moses."},
    {"name": "exodus", "abbreviation": "ex", "number": 2, "chapters": 40, "testament": "old", "type": "historical",
        "author": "Moses", "language": "Hebrew", "description": "Second book of the Bible, traditionally attributed to Moses."},
    {"name": "leviticus", "abbreviation": "lev", "number": 3, "chapters": 27, "testament": "old", "type": "legal", "author": "Moses",
        "language": "Hebrew", "description": "Third book of the Bible, contains laws and regulations for priests and people of Israel."},
    {"name": "numbers", "abbreviation": "num", "number": 4, "chapters": 36, "testament": "old", "type": "historical", "author": "Moses",
        "language": "Hebrew", "description": "Fourth book of the Bible, recounts journey of Israelites from Mount Sinai to Promised Land."},
    {"name": "deuteronomy", "abbreviation": "deut", "number": 5, "chapters": 34, "testament": "old", "type": "legal", "author": "Moses", "language": "Hebrew",
        "description": "Fifth book of the Bible, contains speeches by Moses to Israelites, urging them to keep law and warning of consequences of disobedience."},
    {"name": "joshua", "abbreviation": "josh", "number": 6, "chapters": 24, "testament": "old", "type": "historical", "author": "Joshua",
        "language": "Hebrew", "description": "Sixth book of the Bible, recounts conquest of Promised Land by Israelites under Joshua's leadership."},
    {"name": "judges", "abbreviation": "judg", "number": 7, "chapters": 21, "testament": "old", "type": "historical", "author": "Unknown",
        "language": "Hebrew", "description": "Seventh book of the Bible, contains stories about leaders of Israel known as judges."},
    {"name": "ruth", "abbreviation": "ruth", "number": 8, "chapters": 4, "testament": "old", "type": "historical", "author": "Unknown",
        "language": "Hebrew", "description": "Eighth book of the Bible, tells story of Moabite woman Ruth and her mother-in-law Naomi."},
    {"name": "1samuel", "abbreviation": "1sam", "number": 9, "chapters": 31, "testament": "old", "type": "historical", "author": "Unknown", "language": "Hebrew",
        "description": "Ninth book of the Bible, recounts life of prophet Samuel and reigns of first three kings of Israel: Saul, David, and Solomon."},
    {"name": "2samuel", "abbreviation": "2sam", "number": 10, "chapters": 24, "testament": "old", "type": "historical",
        "author": "Unknown", "language": "Hebrew", "description": "Tenth book of the Bible, continues story of reign of King David."},
    {"name": "1kings", "abbreviation": "1kgs", "number": 11, "chapters": 22, "testament": "old", "type": "historical", "author": "Unknown",
        "language": "Hebrew", "description": "Eleventh book of the Bible, recounts reigns of kings of Israel and Judah after Solomon's death."},
    {"name": "2kings", "abbreviation": "2kgs", "number": 12, "chapters": 25, "testament": "old", "type": "historical", "author": "Unknown",
        "language": "Hebrew", "description": "Twelfth book of the Bible, continues story of reigns of kings of Israel and Judah."},
    {"name": "1chronicles", "abbreviation": "1chr", "number": 13, "chapters": 29, "testament": "old", "type": "historical", "author": "Unknown",
        "language": "Hebrew", "description": "Thirteenth book of the Bible, recounts genealogy of King David and reigns of kings of Israel."},
    {"name": "2chronicles", "abbreviation": "2chr", "number": 14, "chapters": 36, "testament": "old", "type": "historical", "author": "Unknown",
        "language": "Hebrew", "description": "Fourteenth book of the Bible, continues story of reigns of kings of Israel and Judah."},
    {"name": "ezra", "abbreviation": "ezra", "number": 15, "chapters": 10, "testament": "old", "type": "historical", "author": "Unknown",
        "language": "Hebrew", "description": "Fifteenth book of the Bible, tells story of return of exiles to Jerusalem and rebuilding of temple."},
    {"name": "nehemiah", "abbreviation": "neh", "number": 16, "chapters": 13, "testament": "old", "type": "historical", "author": "Unknown",
        "language": "Hebrew", "description": "Sixteenth book of the Bible, continues story of rebuilding of temple and restoration of Jerusalem."},
    {"name": "esther", "abbreviation": "esth", "number": 17, "chapters": 10, "testament": "old", "type": "historical", "author": "Unknown", "language": "Hebrew",
        "description": "Seventeenth book of the Bible, tells story of Jewish girl Esther who becomes queen of Persia and saves her people from destruction."},
    {"name": "job", "abbreviation": "job", "number": 18, "chapters": 42, "testament": "old", "type": "poetry", "author": "Unknown",
        "language": "Hebrew", "description": "Eighteenth book of the Bible, tells story of man named Job who is tested."},
    {"name": "psalms", "abbreviation": "ps", "number": 19, "chapters": 150, "testament": "old", "type": "poetry", "author": "David",
        "language": "Hebrew", "description": "Nineteenth book of the Bible, contains collection of songs and prayers."},
    {"name": "proverbs", "abbreviation": "prov", "number": 20, "chapters": 31, "testament": "old", "type": "wisdom", "author": "Solomon",
        "language": "Hebrew", "description": "Twentieth book of the Bible, contains collection of wise sayings and advice."},
    {"name": "ecclesiastes", "abbreviation": "ecc", "number": 21, "chapters": 12, "testament": "old", "type": "wisdom",
        "author": "Solomon", "language": "Hebrew", "description": "Twenty-first book of the Bible, reflects on meaning of life."},
    {"name": "songofsolomon", "abbreviation": "song", "number": 22, "chapters": 8, "testament": "old", "type": "poetry",
        "author": "Solomon", "language": "Hebrew", "description": "Twenty-second book of the Bible, is love poem."},
    {"name": "isaiah", "abbreviation": "isa", "number": 23, "chapters": 66, "testament": "old", "type": "prophecy", "author": "Isaiah",
        "language": "Hebrew", "description": "Twenty-third book of the Bible, contains prophecies about future of Israel and the Messiah."},
    {"name": "jeremiah", "abbreviation": "jer", "number": 24, "chapters": 52, "testament": "old", "type": "prophecy", "author": "Jeremiah",
        "language": "Hebrew", "description": "Twenty-fourth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "lamentations", "abbreviation": "lam", "number": 25, "chapters": 5, "testament": "old", "type": "poetry", "author": "Jeremiah",
        "language": "Hebrew", "description": "Twenty-fifth book of the Bible, collection of laments for destruction of Jerusalem."},
    {"name": "ezekiel", "abbreviation": "ezek", "number": 26, "chapters": 48, "testament": "old", "type": "prophecy", "author": "Ezekiel",
        "language": "Hebrew", "description": "Twenty-sixth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "daniel", "abbreviation": "dan", "number": 27, "chapters": 12, "testament": "old", "type": "prophecy", "author": "Daniel",
        "language": "Hebrew", "description": "Twenty-seventh book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "hosea", "abbreviation": "hos", "number": 28, "chapters": 14, "testament": "old", "type": "prophecy", "author": "Hosea",
        "language": "Hebrew", "description": "Twenty-eighth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "joel", "abbreviation": "joel", "number": 29, "chapters": 3, "testament": "old", "type": "prophecy", "author": "Joel",
        "language": "Hebrew", "description": "Twenty-ninth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "amos", "abbreviation": "amos", "number": 30, "chapters": 9, "testament": "old", "type": "prophecy", "author": "Amos",
        "language": "Hebrew", "description": "Thirtieth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "obadiah", "abbreviation": "obad", "number": 31, "chapters": 1, "testament": "old", "type": "prophecy", "author": "Obadiah",
        "language": "Hebrew", "description": "Thirty-first book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "jonah", "abbreviation": "jonah", "number": 32, "chapters": 4, "testament": "old", "type": "prophecy", "author": "Jonah",
        "language": "Hebrew", "description": "Thirty-second book of the Bible, contains story of Jonah and the whale."},
    {"name": "micah", "abbreviation": "mic", "number": 33, "chapters": 7, "testament": "old", "type": "prophecy", "author": "Micah",
        "language": "Hebrew", "description": "Thirty-third book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "nahum", "abbreviation": "nah", "number": 34, "chapters": 3, "testament": "old", "type": "prophecy", "author": "Nahum",
        "language": "Hebrew", "description": "Thirty-fourth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "habakkuk", "abbreviation": "hab", "number": 35, "chapters": 3, "testament": "old", "type": "prophecy", "author": "Habakkuk",
        "language": "Hebrew", "description": "Thirty-fifth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "zephaniah", "abbreviation": "zeph", "number": 36, "chapters": 3, "testament": "old", "type": "prophecy", "author": "Zephaniah",
        "language": "Hebrew", "description": "Thirty-sixth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "haggai", "abbreviation": "hag", "number": 37, "chapters": 2, "testament": "old", "type": "prophecy", "author": "Haggai",
        "language": "Hebrew", "description": "Thirty-seventh book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "zechariah", "abbreviation": "zech", "number": 38, "chapters": 14, "testament": "old", "type": "prophecy", "author": "Zechariah",
        "language": "Hebrew", "description": "Thirty-eighth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "malachi", "abbreviation": "mal", "number": 39, "chapters": 4, "testament": "old", "type": "prophecy", "author": "Malachi",
        "language": "Hebrew", "description": "Thirty-ninth book of the Bible, contains prophecies about future of Israel and the coming of the Messiah."},
    {"name": "matthew", "abbreviation": "matt", "number": 40, "chapters": 28, "testament": "new", "type": "gospel", "author": "Matthew",
        "language": "Greek", "description": "Fortieth book of the Bible, contains teachings and deeds of Jesus Christ."},
    {"name": "mark", "abbreviation": "mark", "number": 41, "chapters": 16, "testament": "new", "type": "gospel", "author": "Mark",
        "language": "Greek", "description": "Forty-first book of the Bible, contains teachings and deeds of Jesus Christ."},
    {"name": "luke", "abbreviation": "luke", "number": 42, "chapters": 24, "testament": "new", "type": "gospel", "author": "Luke",
        "language": "Greek", "description": "Forty-second book of the Bible, contains teachings and deeds of Jesus Christ."},
    {"name": "john", "abbreviation": "jn", "number": 43, "chapters": 21, "testament": "new", "type": "gospel", "author": "John",
        "language": "Greek", "description": "Forty-third book of the Bible, contains teachings and deeds of Jesus Christ."},
    {"name": "acts", "abbreviation": "acts", "number": 44, "chapters": 28, "testament": "new", "type": "history", "author": "Luke",
        "language": "Greek", "description": "Forty-fourth book of the Bible, contains history of early Christian church."},
    {"name": "romans", "abbreviation": "rom", "number": 45, "chapters": 16, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Forty-fifth book of the Bible, contains letter from apostle Paul to church in Rome."},
    {"name": "1corinthians", "abbreviation": "1cor", "number": 46, "chapters": 16, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Forty-sixth book of the Bible, contains letter from apostle Paul to church in Corinth."},
    {"name": "2corinthians", "abbreviation": "2cor", "number": 47, "chapters": 13, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Forty-seventh book of the Bible, contains letter from apostle Paul to church in Corinth."},
    {"name": "galatians", "abbreviation": "gal", "number": 48, "chapters": 6, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Forty-eighth book of the Bible, contains letter from apostle Paul to churches in Galatia."},
    {"name": "ephesians", "abbreviation": "eph", "number": 49, "chapters": 6, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Forty-ninth book of the Bible, contains letter from apostle Paul to church in Ephesus."},
    {"name": "philippians", "abbreviation": "phil", "number": 50, "chapters": 4, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Fiftieth book of the Bible, contains letter from apostle Paul to church in Philippi."},
    {"name": "colossians", "abbreviation": "col", "number": 51, "chapters": 4, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Fifty-first book of the Bible, contains letter from apostle Paul to church in Colossae."},
    {"name": "1thessalonians", "abbreviation": "1thess", "number": 52, "chapters": 5, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Fifty-second book of the Bible, contains letter from apostle Paul to church in Thessalonica."},
    {"name": "2thessalonians", "abbreviation": "2thess", "number": 53, "chapters": 3, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Fifty-third book of the Bible, contains letter from apostle Paul to church in Thessalonica."},
    {"name": "1timothy", "abbreviation": "1tim", "number": 54, "chapters": 6, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Fifty-fourth book of the Bible, contains letter from apostle Paul to his disciple Timothy."},
    {"name": "2timothy", "abbreviation": "2tim", "number": 55, "chapters": 4, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Fifty-fifth book of the Bible, contains letter from apostle Paul to his disciple Timothy."},
    {"name": "titus", "abbreviation": "titus", "number": 56, "chapters": 3, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Fifty-sixth book of the Bible, contains letter from apostle Paul to his disciple Titus."},
    {"name": "philemon", "abbreviation": "philem", "number": 57, "chapters": 1, "testament": "new", "type": "epistle", "author": "Paul",
        "language": "Greek", "description": "Fifty-seventh book of the Bible, contains letter from apostle Paul to his friend Philemon."},
    {"name": "hebrews", "abbreviation": "heb", "number": 58, "chapters": 13, "testament": "new", "type": "epistle", "author": "Unknown", "language": "Greek",
        "description": "Fifty-eighth book of the Bible, contains letter to Jewish Christians exhorting them to remain faithful to Christ."},
    {"name": "james", "abbreviation": "jam", "number": 59, "chapters": 5, "testament": "new", "type": "epistle", "author": "James",
        "language": "Greek", "description": "Fifty-ninth book of the Bible, contains letter from apostle James to Jewish Christians."},
    {"name": "1peter", "abbreviation": "1pet", "number": 60, "chapters": 5, "testament": "new", "type": "epistle", "author": "Peter",
        "language": "Greek", "description": "Sixtieth book of the Bible, contains letter from apostle Peter to Christians in Asia Minor."},
    {"name": "2peter", "abbreviation": "2pet", "number": 61, "chapters": 3, "testament": "new", "type": "epistle", "author": "Peter",
        "language": "Greek", "description": "Sixty-first book of the Bible, contains letter from apostle Peter to Christians in Asia Minor."},
    {"name": "1john", "abbreviation": "1jn", "number": 62, "chapters": 5, "testament": "new", "type": "epistle", "author": "John",
        "language": "Greek", "description": "Sixty-second book of the Bible, contains letter from apostle John to Christians."},
    {"name": "2john", "abbreviation": "2jn", "number": 63, "chapters": 1, "testament": "new", "type": "epistle", "author": "John",
        "language": "Greek", "description": "Sixty-third book of the Bible, contains letter from apostle John to Christians."},
    {"name": "3john", "abbreviation": "3jn", "number": 64, "chapters": 1, "testament": "new", "type": "epistle", "author": "John",
        "language": "Greek", "description": "Sixty-fourth book of the Bible, contains letter from apostle John to Christians."},
    {"name": "jude", "abbreviation": "jude", "number": 65, "chapters": 1, "testament": "new", "type": "epistle", "author": "Jude",
        "language": "Greek", "description": "Sixty-fifth book of the Bible, contains letter from apostle Jude to Christians."},
    {"name": "revelation", "abbreviation": "rev", "number": 66, "chapters": 22, "testament": "new", "type": "prophecy",
        "author": "John", "language": "Greek", "description": "Sixty-sixth book of the Bible, contains visions of the future."}
]
